export const SPECIALTIES = [
  "Patologia",
  "Ortopedia",
  "Psicologia",
  "Psiquiatria",
  "Cardiologia",
  "Oftalmologia",
  "Proctologia",
  "Odontologia",
  "Infectologia",
  "Clínica Geral",
  "Hematologia",
  "Cirurgia Geral",
  "Cirurgia Plástica",
  "Neurologia",
  "Urologia",
  "Nutrição",
  "Traumatologia",
];
